---
- include: initialize_groups.yml
  tags:
  - always

- name: Verify Requirements
  hosts: OSEv3
  roles:
  - openshift_health_checker
  vars:
  - r_openshift_health_checker_playbook_context: "install"
  post_tasks:
  - action: openshift_health_check
    args:
      checks:
      - disk_availability
      - package_availability
      - package_version
      - docker_image_availability

- include: ../../common/openshift-cluster/std_include.yml
  tags:
  - always

- include: ../../common/openshift-cluster/config.yml
  vars:
    openshift_cluster_id: "{{ cluster_id | default('default') }}"
    openshift_debug_level: "{{ debug_level | default(2) }}"
    openshift_deployment_subtype: "{{ deployment_subtype | default(none) }}"
    
